---
title: "2_resazurin_calc_analysis"
author: "Samuel Gurr"
date: "2026-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
knitr::opts_knit$set(root.dir = "C:/Users/gurrs/Documents/6_Github_repositories/GurrLab/Predictive_phenomics/RAnalysis") # Sam's
#knitr::opts_knit$set(root.dir = "C:/Users/samuel.gurr/Documents/Github_repositories/EAD-ASEB-Airradians_Popgen_OA/") # Sam's
```


```{r}
library(readxl)
library(stringr)
library(pracma)
library(ggplot2)
library(ggpubr)
```

```{r}

# metadata
metadata_counts <- read.csv("data/Pacific_oyster/resazurin/metadata_larvae_counts.csv", sep=',')
plate_notes     <- metadata_counts %>%  dplyr::select(c('PlateID','Well','Note','X')) %>% dplyr::rename(obs_volume = X)
families        <- read.csv("data/Pacific_oyster/YC26-ebv-crosses-broodpops.csv", sep=',') %>% dplyr::rename(Family = cross)

# outputs from 1_resazurin_raw_compiler
rawdf_72hpf <- read.csv("output/resazurin/rawdf_72hpf.csv")
rawdf_15dpf <- read.csv("output/resazurin/rawdf_15dpf.csv")
rawdf_48dpf <- read.csv("output/resazurin/rawdf_48dpf.csv")
```


```{r  AUC_calculate function}

AUC_calculate <- function (file_in) {

                output.df <- data.frame()
                loop.df_m   <- data.frame(unique(file_in$PlateID)) # call specific df
                loop.df_i   <- data.frame(unique(file_in$Well))  # call specific df
                # Call the cumulative dataframe that we will write to in the for loop below
                output.cumulative.df <- data.frame() # start dataframe 
                output.df            <- data.frame() # start dataframe 
                output.cor.df        <- data.frame() # start dataframe 
                running.df           <- data.frame(matrix(nrow = 1, ncol = 9)) # create dataframe to save cumunalitively during for loop
                colnames(running.df) <- c('Date', 'Treatment', 'PlateID', 'Age', 'Well', 'Family', 'Type', 'Count', 'AUC') # names for columns in the for loop
                          
                          for(m in 1:nrow(loop.df_m)){
                            plate_id      <- data_merged_15dpf %>%   # call specific df
                                                          dplyr::filter(PlateID %in% loop.df_m[m,1])
                                  for(i in 1:nrow(loop.df_i)){
                                    well.over.time       <- plate_id %>% 
                                                                  dplyr::filter(Well %in% loop.df_i[i,1]) %>% 
                                                                  dplyr::arrange(time) %>% 
                                                                  dplyr::mutate(hours = as.numeric(difftime(time, 
                                                                                                            time[1], 
                                                                                                            units = "hours")),
                                                                                delta_florescence = flourescence - flourescence[1],
                                                                                AUC = pracma::trapz(
                                                                                                    hours, 
                                                                                                    flourescence)) %>% 
                                                                  dplyr::select('Date', 'Treatment', 'PlateID', 'Age', 'time', 'Family', 'hours',
                                                                                'Well', 'Type', 'Count', 'AUC', 'delta_florescence')
                                                        
                                    output.cumulative.df <- rbind(output.cumulative.df, well.over.time)
                                    
                                    running.df$Date      <- well.over.time$Date[1]
                                    running.df$Treatment <- well.over.time$Treatment[1]
                                    running.df$PlateID   <- well.over.time$PlateID[1]
                                    running.df$Age       <- well.over.time$Age[1]
                                    running.df$Well      <- well.over.time$Well[1]
                                    running.df$Family    <- well.over.time$Family[1]
                                    running.df$Type      <- well.over.time$Type[1]
                                    running.df$Count     <- well.over.time$Count[1]
                                    running.df$AUC       <- well.over.time$AUC[1]
                                    
                                    output.df <- rbind(output.df,
                                                       running.df) #bind to a cumulative list dataframe
                                    print(output.df) # print to monitor progress
                 
                                    } # wells within plate i end
      
                           } # wells within plate m end
            
            return(output.df)
            
} # function end


```



```{r run AUC_calculate function}

# run function
AUC_calculate_72hpf  <- AUC_calculate(rawdf_72hpf)
AUC_calculate_15dpf  <- AUC_calculate(rawdf_15dpf)
AUC_calculate_48dpf  <- AUC_calculate(rawdf_48dpf)

```

```{r run AUC_calculate function}

meanAUC_blanks_15dpf <- Rmisc::summarySE(
                                  data = (AUC_calculate_15dpf %>% dplyr::filter(Type %in% 'Blank')),
                                  measurevar = 'AUC',
                                  groupvars  = 'PlateID') %>% 
                  dplyr::select(PlateID, AUC) %>% 
                  dplyr::rename(blanks_meanAUC = AUC)


AUC_calculate_15dpf.corrected <- merge(AUC_calculate_15dpf, meanAUC_blanks_15dpf) %>% 
                                      dplyr::filter(!Type %in% 'Blank') %>% # omit blanks
                                      dplyr::mutate(AUC_cor = AUC-blanks_meanAUC,
                                                    # AUC_cor_norm = AUC_cor/Count)
                                                    AUC_cor_norm = dplyr::case_when(
                                                                                    (AUC_cor < 0 | Count == 0) ~ NA,
                                                                                    (AUC_cor > 0 & Count > 0) ~ AUC_cor/Count)) #%>% 
                                      #na.omit()
   
   
AUC_calculate_15dpf.final     <- merge(plate_notes, AUC_calculate_15dpf.corrected) %>% 
                                                dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))

AUC_calculate_15dpf.final.EBV <- merge(AUC_calculate_15dpf.final, families, by = "Family")


AUC_calculate_15dpf.final.EBV.omit <- AUC_calculate_15dpf.final.EBV %>% 
                                             dplyr::filter(!obs_volume %in% 'has no volume') #%>% 
                                #dplyr::filter(!Count < 10)

write.csv(AUC_calculate_15dpf.final.EBV.omit,  "output/resazurin/calculated/calcdf_15dpf.csv")
```

```{r 15 dpf plotting}

delta_abs_figure <- ggplot(
          (output.cumulative.df %>% dplyr::filter(!(Type == 'Sample' & Count == 0))),
           aes(hours, delta_florescence, group = Well)) +
      # geom_point(aes(color = Type)) +
      geom_smooth(aes(color = Type), method = "lm", se = FALSE) +
  facet_wrap(~Treatment,scales = "free")
delta_abs_figure


AUC_cor_by_count <- ggplot(output.cor.df_final_omit, 
                aes(x = Count, y = AUC_cor,  color = Family_EBV)) +
  geom_point(fill = "steelblue")+
  facet_wrap(~Treatment,scales = "free")
AUC_cor_by_count

summary.df <- Rmisc::summarySE(
                      data = (output.cor.df),
                      groupvars = c('Family', 'Treatment'),
                      measurevar = 'AUC_cor_norm')

summary.df_EBV <- merge(summary.df, families, by = "Family") %>% 
                  dplyr::mutate(dam_sire_pop = paste0(dam_pop,"_", sire_pop))

summary.df_EBV <- summary.df_EBV %>% dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))

AUC_cor_by_count_fam <- ggplot(summary.df_EBV, 
                aes(x = as.factor(as.numeric(Family)), y = AUC_cor_norm, color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.2) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")

AUC_cor_by_EBV <- ggplot(summary.df_EBV, 
                aes(x = ebv_mpv, y = AUC_cor_norm, color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.02) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")

AUC_cor_by_DamSire <- ggplot(summary.df_EBV, 
                aes(x = ebv_mpv, y = AUC_cor_norm, color = dam_sire_pop)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.02) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")

AUC_cor_by_count_fam <- ggplot(summary.df_EBV, 
                aes(x = Treatment, y = AUC_cor_norm, 
                    group = as.factor(as.numeric(Family)), 
                    color = dam_sire_pop)) +
  geom_point(fill = "steelblue") +
  geom_smooth(method = "loess", se = TRUE) +
  # geom_errorbar(aes(ymin = AUC_cor_norm - se, ymax = AUC_cor_norm + se), width = 0.2) +
  theme_classic() + 
  facet_wrap(~Family_EBV)


AUC_cor_by_count_fam2 <- ggplot(summary.df_EBV, 
                aes(x = Treatment, y = AUC_cor_norm, group = Family_EBV, color = dam_sire_pop)) +
  geom_point(fill = "steelblue") +
  geom_smooth(method = "loess",               # Apply LOESS smoothing
              se = TRUE,                      # Show 95% CI (grey ribbon)
              level = 0.95,
              span = 0.8)  +
  theme_classic() + 
  facet_wrap(~Family_EBV)



# ?facet_wrap
ggarrange(delta_abs_figure,
          AUC_cor_by_count,
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=2)

ggarrange(
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=1)

pdf("Output/20260401_resazurin.pdf", height = 6, width = 6)
ggarrange(
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=1)
dev.off()

```



Note: call specific df
  * loop.df_m and loop.df_i = columns in **rbind.df_48dpf**
  * plate_id == rows in **data_merged_48dpf** by common plate ID between **rbind.df_48dpf** 
```{r 48 dpf auc calc function}

output.df   <- data.frame()
loop.df_m   <- data.frame(unique(rawdf_48dpf$PlateID))  # call specific df
loop.df_i   <- data.frame(unique(rawdf_48dpf$Well))  # call specific df

# Call the cumulative dataframe that we will write to in the for loop below
output.cumulative.df <- data.frame() # start dataframe 
output.cor.df        <- data.frame() # start dataframe 
output.cor.df_final  <- data.frame() # start dataframe 
running.df           <- data.frame(matrix(nrow = 1, ncol = 9)) # create dataframe to save cumunalitively during for loop
colnames(running.df) <- c('Date', 'Treatment', 'PlateID', 'Age', 'Well', 'Family', 'Type', 'Count', 'AUC') # names for columns in the for loop

for(m in 1:nrow(loop.df_m)){
  plate_id      <- data_merged_48dpf %>%   # call specific df
                                dplyr::filter(PlateID %in% loop.df_m[m,1])
for(i in 1:nrow(loop.df_i)){
  well.over.time       <- plate_id %>% 
                                dplyr::filter(Well %in% loop.df_i[i,1]) %>% 
                                dplyr::arrange(time) %>% 
                                dplyr::mutate(hours = as.numeric(difftime(time, 
                                                                          time[1], 
                                                                          units = "hours")),
                                              delta_florescence = flourescence - flourescence[1],
                                              AUC = pracma::trapz(
                                                                  hours, 
                                                                  flourescence)) %>% 
                                dplyr::select('Date', 'Treatment', 'PlateID', 'Age', 'time', 'Family', 'hours',
                                              'Well', 'Type', 'Count', 'AUC', 'delta_florescence')
                      
  output.cumulative.df <- rbind(output.cumulative.df, 
                                well.over.time)
  
  running.df$Date      <- well.over.time$Date[1]
  running.df$Treatment <- well.over.time$Treatment[1]
  running.df$PlateID   <- well.over.time$PlateID[1]
  running.df$Age       <- well.over.time$Age[1]
  running.df$Well      <- well.over.time$Well[1]
  running.df$Family    <- well.over.time$Family[1]
  running.df$Type      <- well.over.time$Type[1]
  running.df$Count     <- well.over.time$Count[1]
  running.df$AUC       <- well.over.time$AUC[1]
  
   output.df <- rbind(output.df,
                     running.df) #bind to a cumulative list dataframe
   print(output.df) # print to monitor progress
   
   # mean blank AUC by each plate
  mean.AUC.blanks <- mean(
                           (output.df %>% dplyr::filter(Type %in% 'Blank'))$AUC
                          )
   
} # wells within plate end

}

blanks_meanAUC <- Rmisc::summarySE(
                                  data = (output.df %>% dplyr::filter(Type %in% 'Blank')),
                                  measurevar = 'AUC',
                                  groupvars  = 'PlateID') %>% 
                  dplyr::select(PlateID, AUC) %>% 
                  dplyr::rename(blanks_meanAUC = AUC)


output.cor.df <- merge(output.df, blanks_meanAUC) %>% 
                            dplyr::filter(!Type %in% 'Blank') %>% # omit blanks
                            dplyr::mutate(AUC_cor = AUC-blanks_meanAUC,
                                          # AUC_cor_norm = AUC_cor/Count)
                                          AUC_cor_norm = dplyr::case_when(
                                                                          (AUC_cor < 0 | Count == 0) ~ NA,
                                                                          (AUC_cor > 0 & Count > 0) ~
                                                                            AUC_cor/Count)) #%>% 
                            #na.omit()
   

# 
# output.cor.df_final <- merge(plate_notes, output.cor.df) %>% 
#                                                 dplyr::mutate(Family_EBV = 
#                                                    dplyr::case_when(Family > 50 ~ 'Low',
#                                                               Family < 20 ~ 'High'))
# 
# output.cumulative.df <- merge(plate_notes, output.cumulative.df) %>% dplyr::mutate(Family_EBV = 
#                                                    dplyr::case_when(Family > 50 ~ 'Low',
#                                                               Family < 20 ~ 'High'))



output.cor.df_final_omit <- output.cor.df_final %>% 
                                dplyr::filter(!obs_volume %in% 'has no volume') #%>% 
                                #dplyr::filter(!Count < 10)

output.cumulative.df_omit <- output.cumulative.df %>% 
                                dplyr::filter(!obs_volume %in% 'has no volume') #%>% 
                                #dplyr::filter(!Count < 10)

delta_abs_figure <- ggplot(
          (output.cumulative.df), #%>% dplyr::filter(!(Type == 'Sample' & Count == 0))),
           aes(hours, delta_florescence, group = Well)) +
      # geom_point(aes(color = Type)) +
      geom_smooth(aes(color = Type), method = "lm", se = FALSE) +
  facet_wrap(~Treatment,scales = "free")
delta_abs_figure


AUC_cor_by_count <- ggplot(output.cor.df_final_omit, 
                aes(x = Count, y = AUC_cor,  color = Family_EBV)) +
  geom_point(fill = "steelblue")+
  facet_wrap(~Treatment,scales = "free")
AUC_cor_by_count

summary.df <- Rmisc::summarySE(
                      data = (output.cor.df),
                      groupvars = c('Family', 'Treatment'),
                      measurevar = 'AUC_cor')

summary.df_EBV <- merge(summary.df, families, by = "Family") %>% 
                  dplyr::mutate(dam_sire_pop = paste0(dam_pop,"_", sire_pop))

summary.df_EBV <- summary.df_EBV %>% dplyr::mutate(Family_EBV = 
                                                   dplyr::case_when(Family > 50 ~ 'Low',
                                                              Family < 20 ~ 'High'))

AUC_cor_by_count_fam <- ggplot(summary.df_EBV, 
                aes(x = as.factor(as.numeric(Family)), y = AUC_cor, color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor - se, ymax = AUC_cor + se), width = 0.2) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")


AUC_cor_by_EBV <- ggplot(summary.df_EBV, 
                aes(x = ebv_mpv, y = AUC_cor, color = Family_EBV)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor - se, ymax = AUC_cor + se), width = 0.02) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")

AUC_cor_by_DamSire <- ggplot(summary.df_EBV, 
                aes(x = ebv_mpv, y = AUC_cor, color = dam_sire_pop)) +
  geom_point(fill = "steelblue") +
  geom_errorbar(aes(ymin = AUC_cor - se, ymax = AUC_cor + se), width = 0.02) +
  theme_classic() +
  facet_wrap(~Treatment,scales = "free")

AUC_cor_by_DamSire <- ggplot(summary.df_EBV, 
                aes(x =Treatment, y = AUC_cor, 
                    group = as.factor(ebv_mpv),
                    color = as.factor(ebv_mpv))) +
  geom_point(fill = "steelblue") +
  geom_smooth()+
  geom_errorbar(aes(ymin = AUC_cor - se, ymax = AUC_cor + se), width = 0.02) +
  theme_classic() +
  facet_wrap(~Family_EBV)
AUC_cor_by_DamSire

# ?facet_wrap
ggarrange(delta_abs_figure,
          AUC_cor_by_count,
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=2)

ggarrange(
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=1)

pdf("Output/20260401_resazurin.pdf", height = 6, width = 6)
ggarrange(
          AUC_cor_by_count_fam,
          AUC_cor_by_count_fam2,
          nrow=2,
          ncol=1)
dev.off()

```


